version: '3.4'

services:
  backend:
    image: ${DOCKER_REGISTRY-}additivetranslator
    build:
      context: .
      dockerfile: Additive Translator/Dockerfile
  client:
    image: client
    build:
      context: ./EmberApp
      dockerfile: Dockerfile
  proxy:
    image: nginx:mainline